# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Audiobookshelf
version: "2.5.0-11"
slug: audiobookshelf
description: Running an audiobookshelf server
url: "https://github.com/matthewturk/hass-audiobookshelf/tree/main/audiobookshelf"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - media:rw
  - ssl:ro
  - config:rw
ports:
  8081/tcp: 13379
  443/tcp: 13378
environment:
  METADATA_PATH: /data/abs-metadata
  CONFIG_PATH: /data/abs-config
  PORT: "8081"
